-- MySQL Script generated by MySQL Workbench
-- Thu May  3 18:28:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema codingCup
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codingCup
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codingCup` DEFAULT CHARACTER SET utf8 ;
USE `codingCup` ;

-- -----------------------------------------------------
-- Table `codingCup`.`Facturacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codingCup`.`Facturacion` (
  `idFacturacion` INT NOT NULL AUTO_INCREMENT,
  `nombreEquipo` VARCHAR(45) NOT NULL,
  `RFC` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `colonia` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `codigoPostal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFacturacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codingCup`.`Equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codingCup`.`Equipos` (
  `idEquipo` INT NOT NULL AUTO_INCREMENT,
  `referencia` VARCHAR(5) NOT NULL,
  `institucion` VARCHAR(45) NOT NULL,
  `nivelEducativo` VARCHAR(45) NOT NULL,
  `nombreEquipo` VARCHAR(45) NOT NULL,
  `entrenadorEquipo` VARCHAR(45) NOT NULL,
  `correoEntrenador` VARCHAR(45) NOT NULL,
  `RFC` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Estado` CHAR(1) NOT NULL,
  `Facturacion_idFacturacion` INT NOT NULL,
  PRIMARY KEY (`idEquipo`),
  INDEX `fk_Equipos_Facturacion1_idx` (`Facturacion_idFacturacion` ASC),
  CONSTRAINT `fk_Equipos_Facturacion1`
    FOREIGN KEY (`Facturacion_idFacturacion`)
    REFERENCES `codingCup`.`Facturacion` (`idFacturacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codingCup`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codingCup`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `institucion` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `tipo` CHAR(1) NOT NULL DEFAULT 1,
  `Equipos_idEquipo` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuarios_Equipos_idx` (`Equipos_idEquipo` ASC),
  CONSTRAINT `fk_Usuarios_Equipos`
    FOREIGN KEY (`Equipos_idEquipo`)
    REFERENCES `codingCup`.`Equipos` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codingCup`.`Participantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codingCup`.`Participantes` (
  `idParticipantes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `institucion` VARCHAR(45) NOT NULL,
  `nivelEducativo` VARCHAR(45) NOT NULL,
  `nombreEquipo` VARCHAR(45) NOT NULL,
  `nombreEntrenador` VARCHAR(45) NOT NULL,
  `playera` VARCHAR(45) NOT NULL,
  `Equipos_idEquipo` INT NOT NULL,
  PRIMARY KEY (`idParticipantes`),
  INDEX `fk_Participantes_Equipos1_idx` (`Equipos_idEquipo` ASC),
  CONSTRAINT `fk_Participantes_Equipos1`
    FOREIGN KEY (`Equipos_idEquipo`)
    REFERENCES `codingCup`.`Equipos` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codingCup`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codingCup`.`Evento` (
  `idRegistroEvento` INT NOT NULL AUTO_INCREMENT,
  `nombreEvento` VARCHAR(45) NOT NULL,
  `horaInicio` VARCHAR(45) NOT NULL,
  `horaFin` VARCHAR(45) NOT NULL,
  `nombreEquipo` VARCHAR(45) NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `asistencia` CHAR(1) NOT NULL,
  `lugaresDisponibles` INT NOT NULL,
  PRIMARY KEY (`idRegistroEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codingCup`.`Equipos_has_Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codingCup`.`Equipos_has_Evento` (
  `Equipos_idEquipo` INT NOT NULL,
  `Evento_idRegistroEvento` INT NOT NULL,
  PRIMARY KEY (`Equipos_idEquipo`, `Evento_idRegistroEvento`),
  INDEX `fk_Equipos_has_Evento_Evento1_idx` (`Evento_idRegistroEvento` ASC),
  INDEX `fk_Equipos_has_Evento_Equipos1_idx` (`Equipos_idEquipo` ASC),
  CONSTRAINT `fk_Equipos_has_Evento_Equipos1`
    FOREIGN KEY (`Equipos_idEquipo`)
    REFERENCES `codingCup`.`Equipos` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipos_has_Evento_Evento1`
    FOREIGN KEY (`Evento_idRegistroEvento`)
    REFERENCES `codingCup`.`Evento` (`idRegistroEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


select * from facturacion;
INSERT INTO facturacion VALUES(1,'Cadmus','AD23HDS','Benito Juarez','#40','Centro','Uriangato','58500');
INSERT INTO equipos VALUES(1,'ADBCA','ITSUR','Superior','Cadmus','David Morales','david@gmail.com','DSA23HE','123456789','N',1);
INSERT INTO usuarios VALUES(1,'Chema','Lomeli Ibarra','ITSUR','pepe_chiquilin_@hotmail.com','12345','0',1);
INSERT INTO usuarios VALUES(2,'Abraham','Lopez','ITSUR','abraham_@hotmail.com','123','1',1);
INSERT INTO participantes VALUES(1,'Manuel','Ramos','ITSUR','Superior','Cadmus','David Morales','Chica',1);
INSERT INTO participantes VALUES(2,'Adrian','Torres','ITSUR','Superior','Cadmus','David Morales','Mediana',1);
INSERT INTO participantes VALUES(3,'Carlos','Hernandez','ITSUR','Superior','Cadmus','David Morales','Grande',1);
INSERT INTO evento VALUES(1,'Conferencia 1','9:00','10:00','Cadmus','2018-05-20','N','20');




